---
channel: stable
addons:
  grott:
    repository: paralichko/addon-grott
    target: grott
    image: ghcr.io/paralichko/grott/{arch}
  grott-beta:
    repository: paralichko/addon-grott-beta
    target: grott-beta
    image: ghcr.io/paralichko/grott-beta/{arch}
